can_module: SOCKETCAN
can_device: can1
can_baudrate: 1000000
modul_ids: [13, 14]
joint_names: [neck_tilt_joint, neck_pan_joint]
max_accelerations: [1.3, 1.3] # specs [25.133, 16.755]
min_publish_duration: 0.1
horizon: 0.1
OperationMode: position
frequency: 20
force_use_movevel: true
