## joint_names
joint_names: [fr_caster_rotation_joint, fl_caster_rotation_joint, br_caster_rotation_joint, bl_caster_rotation_joint, fr_caster_r_wheel_joint, fl_caster_r_wheel_joint, br_caster_r_wheel_joint, bl_caster_r_wheel_joint]

## joint_state_controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

## twist_controller
twist_controller:
  use_fts: true
  type: hibrid_force_controllers/FTSController
  required_drive_mode: 3
  publish_rate: 50
  max_rot_velocity: 0.2
  max_trans_velocity: 0.2
  Controller:
    SamplingFrequency: 645.0
    DampingFrequency: 20.0
    DampingIntensity: -3.0
    y_reversed: False
    rot_reversed: False
    update_rate: 100.0
    dist_force_scale: 0.1       # Should be between 0 and 1
    backwards_max_force_scale: 0.5
    backwards_max_vel_scale: 0.7 #0.25
    x_force_controller: True
    y_force_controller: True
    rot_controller: True
    linear:
        x_min_force: 3.0        # 5.0
        x_max_force: 120.0
        x_max_vel: 1.1
        x_gain: 2               # 1/b
        x_time_const: 1        # m/b   # 1/(2*pi*Fl)        
        y_min_force: 3.0        # 5.0
        y_max_force: 120.0
        y_max_vel: 1.1
        y_gain: 2               # 1/b
        y_time_const: 1        # m/b   # 1/(2*pi*Fl)
    angular:
        min_torque: 0.1    # 0.5
        max_torque: 30.0
        max_rot_vel: 1.8
        gain: 1
        time_const: 0.25
  defaults: # default settings for all wheels, can per overwritten per wheel
    steer_ctrl: # Parameters for tuning Impedance-Controller
      spring: 15.0
      damp: 2.75
      virt_mass: 0.1 
      d_phi_max: 12.0
      dd_phi_max: 40.0

  wheels: &wheels # start front left, counter-clockwise for base_drive_chain compatibility
    - steer: fl_caster_rotation_joint
      drive: fl_caster_r_wheel_joint
      steer_neutral_position: 180.0
    - steer: bl_caster_rotation_joint
      drive: bl_caster_r_wheel_joint
      steer_neutral_position: 180.0
    - steer: br_caster_rotation_joint
      drive: br_caster_r_wheel_joint
      steer_neutral_position: 180.0
    - steer: fr_caster_rotation_joint
      drive: fr_caster_r_wheel_joint
      steer_neutral_position: 180.0

## odometry_controller
odometry_controller:
  type: cob_omni_drive_controller/OdometryController
  publish_rate: 50
  frame_id: "/odom_combined"
  child_frame_id: "/base_footprint"
  cov_pose: 0.1
  cov_twist: 0.1
  defaults: # default settings for all wheels, can per overwritten per wheel
    wheel_radius: 0.080 # Radius of the wheels in [m]
  wheels: *wheels
